FROM alpine:latest
LABEL Description="Application sources container"

ENV PS1='\[\033[1;32m\]🐳  \[\033[1;36m\][\u@\h] \[\033[1;34m\]\w\[\033[0;35m\] \[\033[1;36m\]# \[\033[0m\]'

COPY . /src

WORKDIR /src
VOLUME ["/src"]
