<?php

namespace Tests\Unit;

use App\Models\Specifications;
use Tests\TestCase;

class SpecificationsTest extends TestCase
{
    public function testAutogeneratedAliasFromNameTest()
    {
        $property = Specifications::create([
            'name' => 'Example Specification',
            'type' => 2
        ]);

        $this->assertEquals('example-specification', $property->slug);
    }
}
